spring.application.name=BrainStack

# ==========================
# ? Configuration Base de Données MySQL
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/brainstack_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# ? JPA / Hibernate
# ==========================
# Création automatique des tables à partir des entités
spring.jpa.hibernate.ddl-auto=update

# Dialecte MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Affichage des requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Taille maximale d?un fichier individuel
spring.servlet.multipart.max-file-size=500MB
# Taille maximale d?une requête (plusieurs fichiers possibles)
spring.servlet.multipart.max-request-size=500MB
