spring.application.name=BrainStack

# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:neurocare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=BrainStack
spring.datasource.password=BrainStack

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activer la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8001

# Springdoc OpenAPI configuration
springdoc.api-docs.path=/api/v1
