
spring.application.name=BrainStack

# DB Configuration :
spring.datasource.url=jdbc:mysql://localhost:3306/brainstack_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Web Server (Tomcat) configuration :
server.port=8089
server.servlet.context-path=/api/v1

# AI Microservice Configuration :
ai.microservice.url=http://localhost:5000
ai.microservice.timeout=5000
ai.microservice.retry-attempts=3

# === MAIL CONFIGURATION ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nourbbbb430@gmail.com
spring.mail.password=rbjxipuvdoduuzqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
# Taille maximale d?un fichier individuel
spring.servlet.multipart.max-file-size=500MB
# Taille maximale d?une requ�te (plusieurs fichiers possibles)
spring.servlet.multipart.max-request-size=500MB

